
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbapp
spec:
  selector:
    matchLabels:
      app: sbapp
  replicas: 3
  template:
    metadata:
      labels:
        app: sbapp
    spec:
      containers:
      - name: sbapp
        image: veereshvishu/health-insure-me:3.0
        imagePullPolicy: Always
        ports:
        - name: sbapp
          containerPort: 8082
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: sbapp-lb
  labels:
    app: sbapp
spec:
  type: LoadBalancer
  ports:
  - port: 8089
    targetPort: 8082
  selector:
    app: sbapp


