apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure-deploy
  labels:
    app: medicure-mvn-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: medicure-mvn-app
  template:
    metadata:
      labels:
        app: medicure-mvn-app
    spec:
      containers:
      - name: medicure-mvn-container
        image: rahul9711/medicure:1.0
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: medicure-np-service
  labels:
    app: medicure-mvn-app
spec:
  selector:
    app: medicure-mvn-app

  type: NodePort
  ports:
  - nodePort: 31000
    port: 8082
    targetPort: 8082
