apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbapp
spec:
  selector:
    matchLabels:
      app: sbapp
  replicas: 3
  template:
    metadata:
      labels:
        app: sbapp
    spec:
      containers:
      - name: sbapp
        image: nik848/medicure:1.0
        imagePullPolicy: Always
        ports:
        - name: sbapp
          containerPort: 8082
          protocol: TCP


